INSERT INTO towerdefense.maps (MAP_ID) VALUES (1);
INSERT INTO towerdefense.maps (MAP_ID) VALUES (2);

INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 3, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 5, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (0, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 3, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 5, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (1, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 3, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 5, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (2, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 3, 1, 'UP_RIGHT_TURN');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 4, 1, 'HORIZONTAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 5, 1, 'UP_LEFT_TURN');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (3, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 3, 1, 'VERTICAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 5, 1, 'VERTICAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (4, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 0, 1, 'HORIZONTAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 1, 1, 'HORIZONTAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 2, 1, 'HORIZONTAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 3, 1, 'DOWN_RIGHT_TURN');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 5, 1, 'VERTICAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (5, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 3, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 5, 1, 'DOWN_LEFT_TURN');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 6, 1, 'HORIZONTAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 7, 1, 'HORIZONTAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 8, 1, 'HORIZONTAL_STRAIGHT');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (6, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 3, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 5, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (7, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 3, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 5, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (8, 9, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 0, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 1, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 2, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 3, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 4, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 5, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 6, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 7, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 8, 1, 'EMPTY_FIELD');
INSERT INTO towerdefense.fields_st (X, Y, MAP_ID, FIELD_TYPE) VALUES (9, 9, 1, 'EMPTY_FIELD');

INSERT INTO towerdefense.rounds (ROUND_ID) VALUES (1);
INSERT INTO towerdefense.entities_bt (DAMAGE, ENTITY_TYPE) VALUES (10, 'ONI');
INSERT INTO towerdefense.entities_bt (DAMAGE, ENTITY_TYPE) VALUES (10, 'ARCHER');
INSERT INTO towerdefense.entities_bt (DAMAGE, ENTITY_TYPE) VALUES (15, 'LONGBOW_ARCHER');
INSERT INTO towerdefense.saved_games (SAVED_GAME_ID,MAP_ID ,MONEY, ROUND, NAME, HP) VALUES (1, 1,100, 1, 'game1', 100);
INSERT INTO towerdefense.map_has_entities_jt (ENTITY_ID, SAVED_GAME_ID,ENTITY_TYPE) VALUES (1, 1, 'ARCHER');
INSERT INTO towerdefense.defenders (ENTITY_ID, FIRE_RATE, `RANGE`, COST, ROUND) VALUES (2, 2, 4, 20, 1);
INSERT INTO towerdefense.defenders (ENTITY_ID, FIRE_RATE, `RANGE`, COST, ROUND) VALUES (3, 1, 6, 25, 1);
INSERT INTO towerdefense.attackers (ENTITY_ID, SPEED, HP, SHIELD, LOOT, ROUND_ID) VALUES (1, 3, 60, 0, 15, 1);
INSERT INTO towerdefense.map_has_entities_jt (ENTITY_ID, SAVED_GAME_ID, X, Y, ENTITY_TYPE) VALUES (2, 1, 2, 2, 'ARCHER');
INSERT INTO towerdefense.map_has_entities_jt (ENTITY_ID, SAVED_GAME_ID, X, Y, ENTITY_TYPE) VALUES (3, 1, 2, 3, 'LONGBOW_ARCHER');
